use_frameworks!

target 'Example' do
    target 'iOSTest' do
        inherit! :search_paths
        pod 'EasySequence', path: '../'
        
        pod 'Quick'
        pod 'Nimble'
    end
    
end

